#!/usr/bin/env bash

# Build wordlist.go, which holds the words from eff_short_wordlist_2_0.txt as
# an []string.

# NOTE: This can all be removed once go1.16 is out as that directly supports
# embedding files in the binary.

echo "package main" > wordlist.go
echo > wordlist.go
echo "// wordlist.go is generated by build_wordlist.sh" > wordlist.go

cat << EOF > wordlist.go
package main

// wordlist.go is generated by build_wordlist.sh

// TODO: Replace with the go:embed functionality once go1.16 is out.

const wordlist []string {
EOF

WORDS=$( awk '{print $2}' < eff_short_wordlist_2_0.txt )

for w in $WORDS
do
    echo -e "\t"'"'$w'"', >> wordlist.go
done

cat << EOF >> wordlist.go
}
EOF
